In [304]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import neighbors
from sklearn.model_selection import train_test_split

In [305]:
data=pd.read_csv('train.csv')
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [306]:
data2=data.drop(['PassengerId', 'Name', 'Ticket', 'Fare', 'Cabin','Age'], axis=1 )
data2.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked'], dtype='object')

In [307]:
data2.head()

Survived  Pclass     Sex  SibSp  Parch Embarked
0         0       3    male      1      0        S
1         1       1  female      1      0        C
2         1       3  female      0      0        S
3         1       1  female      1      0        S
4         0       3    male      0      0        S

In [308]:
le=LabelEncoder()
data2['Sex']=le.fit_transform(data2['Sex'])
data2['Embarked']=le.fit_transform(data2['Embarked'])
data2.head()

Survived  Pclass  Sex  SibSp  Parch  Embarked
0         0       3    1      1      0         2
1         1       1    0      1      0         0
2         1       3    0      0      0         2
3         1       1    0      1      0         2
4         0       3    1      0      0         2

In [317]:
x=data2.drop(["Pclass"], axis=1)
y=data2['Pclass']

In [330]:
for i in range(1, 10):
  X=data2
  y=data2["Pclass"]
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
  knn=neighbors.KNeighborsClassifier(n_neighbors=i)
  knn.fit(X_train, y_train)
  y_pred=knn.predict(X_test)
  print('k-value', i)
  print('accuracy score', accuracy_score(y_pred, y_test))
  print(confusion_matrix(y_pred, y_test))

k-value 1
accuracy score 0.9662921348314607
[[ 68   5   0]
 [  2  48   1]
 [  1   0 142]]
k-value 2
accuracy score 0.951310861423221
[[ 68   5   0]
 [  3  48   5]
 [  0   0 138]]
k-value 3
accuracy score 0.9550561797752809
[[ 69   5   0]
 [  2  46   3]
 [  0   2 140]]
k-value 4
accuracy score 0.951310861423221
[[ 71   7   0]
 [  0  44   4]
 [  0   2 139]]
k-value 5
accuracy score 0.9550561797752809
[[ 67   5   0]
 [  4  46   1]
 [  0   2 142]]
k-value 6
accuracy score 0.947565543071161
[[ 67   8   0]
 [  4  44   1]
 [  0   1 142]]
k-value 7
accuracy score 0.947565543071161
[[ 67   7   0]
 [  4  44   1]
 [  0   2 142]]
k-value 8
accuracy score 0.947565543071161
[[ 67   5   0]
 [  4  44   1]
 [  0   4 142]]
k-value 9
accuracy score 0.947565543071161
[[ 67   5   0]
 [  4  44   1]
 [  0   4 142]]
