In [263]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [264]:
data=pd.read_csv('train.csv')
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [265]:
data2=data.drop(['PassengerId', 'Name', 'Ticket', 'Fare', 'Cabin','Age'], axis=1 )
data2.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked'], dtype='object')

In [266]:
data2.head()

Survived  Pclass     Sex  SibSp  Parch Embarked
0         0       3    male      1      0        S
1         1       1  female      1      0        C
2         1       3  female      0      0        S
3         1       1  female      1      0        S
4         0       3    male      0      0        S

In [267]:
le=LabelEncoder()
data2['Sex']=le.fit_transform(data2['Sex'])
data2['Embarked']=le.fit_transform(data2['Embarked'])
data2.head()

Survived  Pclass  Sex  SibSp  Parch  Embarked
0         0       3    1      1      0         2
1         1       1    0      1      0         0
2         1       3    0      0      0         2
3         1       1    0      1      0         2
4         0       3    1      0      0         2

In [285]:
for i in data2:
  y=data2[i]
  X=data2.drop([i], axis=1)
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
  clf=svm.SVC(gamma=0.01, C=100)
  clf.fit(X_train, y_train)
  y_pred=clf.predict(X_test)
  print('accuracy score', accuracy_score(y_pred, y_test))
  print(confusion_matrix(y_pred, y_test))
  

accuracy score 0.8352059925093633
[[149  27]
 [ 17  74]]
accuracy score 0.5767790262172284
[[ 16   4   9]
 [  7   6   2]
 [ 48  43 132]]
accuracy score 0.8089887640449438
[[ 75  29]
 [ 22 141]]
accuracy score 0.6891385767790262
[[167  43   8   1   2   0   0]
 [ 11  17   4   5   5   3   1]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]]
accuracy score 0.7940074906367042
[[200  35  12   1   1   1]
 [  1   7   4   0   0   0]
 [  0   0   5   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]]
accuracy score 0.700374531835206
[[  0   0   0]
 [  0   0   0]
 [ 54  26 187]]
