In [3]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB,BernoulliNB 

In [35]:
data=pd.read_csv('train.csv')
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Sex"]=le.fit_transform(data["Sex"])
data["Embarked"]=le.fit_transform(data["Embarked"])
X=data.drop(['Survived',"Name", "Cabin", "PassengerId", "Ticket"], axis=1)
y=data["Survived"]
X.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  22.0      1      0   7.2500         2
1       1    0  38.0      1      0  71.2833         0
2       3    0  26.0      0      0   7.9250         2
3       1    0  35.0      1      0  53.1000         2
4       3    1  35.0      0      0   8.0500         2

In [13]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=0)

In [39]:
from sklearn.naive_bayes import BernoulliNB
model=BernoulliNB()
y_pred=model.fit(X_train, y_train).predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("accuracy_score", accuracy_score(y_pred, y_test))
print(confusion_matrix(y_pred, y_test))

accuracy_score 0.7715355805243446
[[131  35]
 [ 26  75]]


In [54]:
data1=data.drop(["Name", "PassengerId", "Ticket", "Cabin"], axis=1)
data1.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [79]:
def Dependent_var(X, y):
  from sklearn.model_selection import train_test_split
  X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=0)  
  from sklearn.naive_bayes import BernoulliNB
  model=BernoulliNB()
  y_pred=model.fit(X_train, y_train).predict(X_test) 
  from sklearn.metrics import accuracy_score,confusion_matrix
  print("accuracy_score", accuracy_score(y_pred, y_test))
  print(confusion_matrix(y_pred, y_test))



In [83]:
Dependent_var(data1, data1['Pclass'])

accuracy_score 0.5917602996254682
[[ 30   9  24]
 [  8  10   6]
 [ 32  30 118]]


In [82]:
Dependent_var(data1, data1['Survived'])

accuracy_score 1.0
[[157   0]
 [  0 110]]


In [85]:
Dependent_var(data1, data1['Sex'])

accuracy_score 1.0
[[ 98   0]
 [  0 169]]


In [86]:
Dependent_var(data1, data1['SibSp'])

accuracy_score 0.9250936329588015
[[182   0   0   0   0   0   0]
 [  0  65   8   7   2   1   2]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]]


In [87]:
Dependent_var(data1, data1['Parch'])

accuracy_score 0.8913857677902621
[[198   0   0   0   0]
 [  0  39  26   1   0]
 [  0   1   1   0   1]
 [  0   0   0   0   0]
 [  0   0   0   0   0]]


In [88]:
Dependent_var(data1, data1['Embarked'])

accuracy_score 0.9176029962546817
[[ 49   0   0]
 [  0   0   0]
 [  0  22 196]]
