# 1. Create a 3x3x3 array with random values 

In [12]:
import numpy as np
a=np.random.rand(3,3,3)
a

array([[[0.09382408, 0.12254333, 0.49678262],
        [0.95119062, 0.97029204, 0.19256189],
        [0.18154204, 0.72531894, 0.72724634]],

       [[0.31284632, 0.58113825, 0.37941119],
        [0.96639795, 0.84775685, 0.3067488 ],
        [0.86164643, 0.2381181 , 0.2872596 ]],

       [[0.83199936, 0.85253127, 0.11916356],
        [0.72852594, 0.06078212, 0.76016004],
        [0.87034571, 0.57814861, 0.97697456]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [15]:
b=np.diag([1,2,3,4])
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [42]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [44]:
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.43713865 0.47503947 0.80626543]
 [0.08081618 0.11524137 0.00113701]
 [0.77764153 0.53954629 0.37845667]]
After normalization:
[[0.54153056 0.58860481 1.        ]
 [0.09896456 0.14172194 0.        ]
 [0.96444803 0.66872473 0.46864531]]



5.  How to find common values between two arrays?

In [46]:
array1 = np.array([0, 10, 20, 40, 60])
print(array1)
array2 = [10, 30, 40]
print(array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

[ 0 10 20 40 60]
[10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [48]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("yesterday",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

yesterday 2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [51]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
np.equal(a,b)

array([ True,  True,  True,  True])

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [60]:
x=np.random.rand(10)
a=x.max()
a=0
print(x)
print(a)

[0.1278013  0.98788004 0.52980495 0.13466399 0.017778   0.10613733
 0.09170721 0.67459364 0.11431566 0.34629603]
0


# 9. How to print all the values of an array?

In [67]:
import numpy 
a=numpy.arange(10000).reshape(250,40)
print(a)

[[   0    1    2 ...   37   38   39]
 [  40   41   42 ...   77   78   79]
 [  80   81   82 ...  117  118  119]
 ...
 [9880 9881 9882 ... 9917 9918 9919]
 [9920 9921 9922 ... 9957 9958 9959]
 [9960 9961 9962 ... 9997 9998 9999]]


# 10.Subtract the mean of each row of a matrix

In [79]:
a=np.random.rand(2,2)
print(a)
b=np.mean(a[1,1])
print(b)
c=np.mean(a[1,0])
print(c)
sub=b-c
print(sub)

[[0.55602811 0.03459418]
 [0.23316678 0.27127161]]
0.2712716059948689
0.23316678043548256
0.038104825559386324


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [83]:
a=np.array([1,2,3,4])
b=1+a
b

array([2, 3, 4, 5])

# 12.How to get the diagonal of a dot product?

In [98]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(0,5,(3,3))
c=np.diagonal(a.dot(b))
print(a)
print(b)
print(c)

[[9 5 0]
 [1 4 6]
 [7 5 0]]
[[2 3 1]
 [0 0 3]
 [2 1 1]]
[18  9 22]


# 13.How to find the most frequent value in an array?

In [104]:
import statistics 
from statistics import mode 
list = [2, 1, 2, 2, 1, 3] 
print(list)
def most_common(list): 
    return(mode(list))
most_common(list)


[2, 1, 2, 2, 1, 3]


2

# 14.How to get the n largest values of an array

In [105]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [106]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
